name: Generate Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1
      with:
        version: 2023.3.4.0

    - name: Generate documentation
      run: msbuild Documentation/CodeDocumentation.shfbproj /p:configuration="Release" /m /verbosity:minimal
      
    - name: Clean up docs folder
      shell: powershell
      run: Remove-Item -Path docs/* -Recurse -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: Documentation/build/*
        if-no-files-found: error

    - name: Move documentation to docs folder
      run: Move-Item -Path Documentation/build/* -Destination docs/
