name: Generate Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install SHFB
      run: choco install sandcastlehelpfilebuilder

    - name: Generate documentation
      run: shfb --project Documentation/CodeDocumentation.shfbproj

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: Documentation/build/*
        if-no-files-found: error

    - name: Move documentation to docs folder
      run: Move-Item -Path Documentation/build/* -Destination docs/
