name: Generate Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SHFB
      run: choco install sandcastlehelpfilebuilder

    - name: Generate documentation
      run: shfb --project Documentation/CodeDocumentation.shfbproj

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: Documentation/build/*
        if-no-files-found: error

    - name: Move documentation to docs folder
      run: mv Documentation/build/* docs/
